### ISSUE TITLE
[BUG]:  ionic production build error kind undefined

### ISSUE THREAD

**Issue by gchokeen** [jrquick17/ionic4-auto-complete#35]
# I'm submitting a

- [ ] Bug report

## Description

When try to build ionic project for production `ionic build --prod` then I'm getting this error `TypeError: Cannot read property 'kind' of undefined` 

```
ERROR in ./node_modules/ionic4-auto-complete/fesm2015/ionic4-auto-complete.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/App/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/App/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/App/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/App/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/App/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/App/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/App/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/App/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/App/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/App/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/App/node_modules/typescript/lib/typescript.js:16599:21)
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:build:production exited with exit code 1.
```

### Version Information

```
   Ionic CLI                     : 5.2.3 
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0
```

### Browser

- [ ] Chrome - 78.0.3904.108 (Official Build) (64-bit)

**Comment by jrquick17** [comment]
@gchokeen I am unable to reproduce this. [I changed the dependencies in the demo to match yours](https://github.com/jrquick17/ionic4-auto-complete/tree/issue-35) and `ionic build --prod` completes with no issues. Can you share more to reproduce the issue?

**Comment by gchokeen** [comment]
@jrquick17 I posted here the package.json to reproduce it 
```
{
  "name": "ionicApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/pwa": "^0.803.9",
    "@angular/router": "~8.1.2",
    "@elastic/elasticsearch": "^7.5.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@ngxs/devtools-plugin": "^3.5.1",
    "@ngxs/form-plugin": "^3.5.1",
    "@ngxs/logger-plugin": "^3.5.1",
    "@ngxs/storage-plugin": "^3.5.1",
    "@ngxs/store": "^3.5.1",
    "core-js": "^2.5.4",
    "elasticsearch-browser": "^16.5.0",
    "ionic-tooltips": "^3.1.0",
    "ionic4-auto-complete": "^2.4.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project"
}
```

**Comment by bcleuing** [comment]
I also encountered the same error and solved it by updating all `@angular-devkit` dependencies from version `8.1.2` to version `8.3.20`.

Reference: https://github.com/jrquick17/ionic4-auto-complete/blob/master/package.json

Below is the `devDependencies` of my `package.json`
```
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.20",
    "@angular-devkit/build-angular": "^0.803.20",
    "@angular-devkit/core": "^8.3.20",
    "@angular-devkit/schematics": "^8.3.20",
    "@angular/cli": "^8.3.20",
    "@angular/compiler": "^8.2.14",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
```

**Comment by gchokeen** [comment]
@bcleuing Thank you so much, thats done the trick
