### ISSUE TITLE
New error when compile to production

### ISSUE THREAD

**Issue by viruzck** [jrquick17/ionic4-auto-complete#48]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Hi i have new a error when run "ionic cordova build android --prod", in my angular.json file i have @ionic/angular-toolkit and i use ionic4-auto-complete v1.10.0

```
ERROR in ./node_modules/ionic4-auto-complete/fesm5/ionic4-auto-complete.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30)
    at Object.forEachChild (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16370:24)
    at checkNodeForDecorators (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16265:21)
    at checkNodeForDecorators (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16322:24)
    at checkNodeForDecorators (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16333:24)
    at checkNodeForDecorators (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (D:\Erick\Git\XXXXXXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16229:21)
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:ionic-cordova-build:production --platform=android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

### Version Information

```
Ionic:

   Ionic CLI                     : 5.4.15 (C:\Program Files (x86)\Nodist\bin\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 14 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\Erick\AppData\Local\Android\Sdk)
   NodeJS            : v8.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by qamrulhaque** [comment]
Getting same error, it was working few days ago

ERROR in ./node_modules/ionic4-auto-complete/fesm2015/ionic4-auto-complete.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16599:21)
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build:production --platform=android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by qamrulhaque** [comment]
Getting same error. It was working few days ago.

`ERROR in ./node_modules/ionic4-auto-complete/fesm2015/ionic4-auto-complete.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/var/www/html/ionic/pangea-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/var/www/html/ionic/pangea-app/node_modules/typescript/lib/typescript.js:16599:21)
[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build:production --platform=android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.`

**Comment by qamrulhaque** [comment]
Getting same error. It was working few days ago.

**Comment by moneycoach2019** [comment]
same here

**Comment by jrquick17** [comment]
I am unable to reproduce this issue in v0.10.1 using [this project](https://github.com/jrquick17/i4ac-test/tree/ng7) with `cordova-android@8.1.0`. Can anyone share code where this error occurs? Feel free to make changes to the test project.

**Comment by moneycoach2019** [comment]
After updating to the newest versions (the same as you have in your test project), the compile in production mode works flawlessly

**Comment by qamrulhaque** [comment]
Updating @angular-devkit/build-angular from 0.801.2 to 0.803.23 works.
