### ISSUE TITLE
[BUG] Issue when building in production environment

### ISSUE THREAD

**Issue by tdervilyIAD** [jrquick17/ionic4-auto-complete#62]
Hi,

I've got the following errors when building my app with `--prod` flag :

```
ERROR in ./node_modules/ionic4-auto-complete/fesm2015/ionic4-auto-complete.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/u24890/Dev/perso/the-sorority/the-sorority-mobile/node_modules/typescript/lib/typescript.js:16599:21)
```

### Version Information

```
ionic4-auto-complete: 2.6.0
@angular/cli: 8.1.2
@ionic/angular: ^4.7.1
typescript: ~3.4.3
```

**Comment by jrquick17** [comment]
@tdervilyIAD I lowered the dependencies in the demo project to match your and was unable to reproduce this issue. Could you share your full package.json`?
